# Generated by Django 4.2.10 on 2024-02-14 01:23

from django.db import migrations

def insert_status(apps, schema_editor):
    Status = apps.get_model('core', 'Status')
    statuses = [
        'Gig Ready',
        'Passable'
        'Needs Work',
        'Used To Know It',
        "Don't Know"
    ]
    for s in statuses:
        Status.objects.create(name=s)

def reverse_insert_status(apps, schema_editor):
    Status = apps.get_model('core', 'Status')
    Status.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_status_song'),
    ]

    operations = [
        migrations.RunPython(insert_status, reverse_insert_status)
    ]
