# Generated by Django 4.2.10 on 2024-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_insert_song_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
