version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - ./songmanager/.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/app

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: songmanager