version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - ./songmanger/.env
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: songmanager
      MYSQL_USER: songmanager
      MYSQL_PASSWORD: password